// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("Style", "IDE0290:Use primary constructor", Justification = "<Pending>", Scope = "member", Target = "~M:Codes.Application.Codes.Commands.AddCode.AddCodeCommand.AddCodeHandler.#ctor(Codes.Application.Services.Persistence.ICodesDbContext)")]
[assembly: SuppressMessage("Style", "IDE0290:Use primary constructor", Justification = "<Pending>", Scope = "member", Target = "~M:Codes.Application.Codes.Commands.EditCode.EditCodeCommand.EditCodeHandler.#ctor(Codes.Application.Services.Persistence.ICodesDbContext)")]
[assembly: SuppressMessage("Style", "IDE0290:Use primary constructor", Justification = "<Pending>", Scope = "member", Target = "~M:Codes.Application.Codes.Commands.EnableCode.EnableCodeCommand.EnableCodeHandler.#ctor(Codes.Application.Services.Persistence.ICodesDbContext)")]
[assembly: SuppressMessage("Style", "IDE0290:Use primary constructor", Justification = "<Pending>", Scope = "member", Target = "~M:Codes.Application.Codes.Queries.GetCode.GetCodeQuery.GetCodeHandler.#ctor(Codes.Application.Services.Persistence.ICodesDbContext)")]
[assembly: SuppressMessage("Style", "IDE0290:Use primary constructor", Justification = "<Pending>", Scope = "member", Target = "~M:Codes.Application.Codes.Queries.SearchCodes.SearchCodesQuery.SearchCodesHandler.#ctor(Codes.Application.Services.Persistence.ICodesDbContext)")]
[assembly: SuppressMessage("Style", "IDE0290:Use primary constructor", Justification = "<Pending>", Scope = "member", Target = "~M:Codes.Application.CodeTypes.Commands.AddCodeType.AddCodeTypeCommand.AddCodeTypeHandler.#ctor(Codes.Application.Services.Persistence.ICodesDbContext)")]
[assembly: SuppressMessage("Style", "IDE0290:Use primary constructor", Justification = "<Pending>", Scope = "member", Target = "~M:Codes.Application.CodeTypes.Commands.DeleteCodeType.DeleteCodeTypeCommand.DeleteCodeTypeHandler.#ctor(Codes.Application.Services.Persistence.ICodesDbContext)")]
[assembly: SuppressMessage("Style", "IDE0290:Use primary constructor", Justification = "<Pending>", Scope = "member", Target = "~M:Codes.Application.CodeTypes.Commands.EditCodeType.EditCodeTypeCommand.EditCodeTypeHandler.#ctor(Codes.Application.Services.Persistence.ICodesDbContext)")]
[assembly: SuppressMessage("Style", "IDE0290:Use primary constructor", Justification = "<Pending>", Scope = "member", Target = "~M:Codes.Application.CodeTypes.Queries.GetCodeType.GetCodeTypeQuery.GetCodeTypeHandler.#ctor(Codes.Application.Services.Persistence.ICodesDbContext)")]
[assembly: SuppressMessage("Style", "IDE0290:Use primary constructor", Justification = "<Pending>", Scope = "member", Target = "~M:Codes.Application.CodeTypes.Queries.SearchCodeTypes.SearchCodeTypesQuery.SearchCodeTypesHandler.#ctor(Codes.Application.Services.Persistence.ICodesDbContext)")]
[assembly: SuppressMessage("Style", "IDE0290:Use primary constructor", Justification = "<Pending>", Scope = "member", Target = "~M:Codes.Application.CodeTypes.Commands.AddCodeType2.AddCodeTypeCommand2.AddCodeTypeHandler2.#ctor(Codes.Application.Services.Persistence.ICodesDbContext)")]
[assembly: SuppressMessage("Style", "IDE0290:Use primary constructor", Justification = "<Pending>", Scope = "member", Target = "~M:Codes.Application.Codes.Commands.AddCode.AddCodeCommand.AddCodeHandler.#ctor(Codes.Application.Services.Persistence.ICodesDbContext,Codes.Application.Services.Audit.IAuditService)")]
[assembly: SuppressMessage("Style", "IDE0290:Use primary constructor", Justification = "<Pending>", Scope = "member", Target = "~M:Codes.Application.CodeTypes.Commands.AddCodeType.AddCodeTypeCommand.AddCodeTypeHandler.#ctor(Codes.Application.Services.Persistence.ICodesDbContext,Codes.Application.Services.Audit.IAuditService)")]
[assembly: SuppressMessage("Style", "IDE0290:Use primary constructor", Justification = "<Pending>", Scope = "member", Target = "~M:Codes.Application.CodeTypes.Commands.AddCodeType3.AddCodeTypeCommand3.AddCodeTypeHandler.#ctor(Codes.Application.Services.Persistence.ICodesDbContext,Codes.Application.Services.Audit.IAuditService)")]
