version: '3.4'

services:
  codes.api:
    image: ${DOCKER_REGISTRY-}codesapi
    build:
      context: .
      dockerfile: Codes\Codes.Api\Dockerfile

  audit.api:
    image: ${DOCKER_REGISTRY-}auditapi
    build:
      context: .
      dockerfile: Audit\Audit.Api\Dockerfile

  rabbitmq:
    image: rabbitmq:management
    ports:
    - 5672:5672
    - 15672:15672
